job("chield_job")
{
  triggers 
    {
        upstream(projects='maven-seed-job',threshold='SUCCESS')
    }
  scm
  {
        github(ownerAndProject='jenkins-docs/simple-java-maven-app',branch='main')
  }
  steps 
  {
         maven 
         {
            goals('package')
            mavenInstallation('maven')  
         }
  }
  publishers 
  {
        archiveJunit('target/surefire-reports/*.xml')
        archiveArtifacts('target/*.jar')
  }
}
